[Limitations]
    # How many chunks should players be able to load per world? Use -1 for infinite.
    # Allowed range: -1 ~ 1000 - Default: -1
    maxLoadedChunksPerPlayer = -1

    # After how many minutes of offline time should players' chunk loaders be disabled? Use -1 to disable the inactivity timeout.
    # Allowed range: -1 ~ 525600 - Default: 10080
    inactivityTimeout = 10080

    # Chunk loaders from before version 1.2.0 are not bound to a player. Should these chunk loaders' loaded chunks stay loaded?
    # Allowed values: true, false - Default: true
    allowLegacyLoadedChunks = true

    # Can players use the chunk loader map? If false, players will see the message 'The chunk loader map is disabled on this server'.
    # Allowed values: true, false - Default: true
    canPlayersUseMap = true

[General]
    # In what radius should the Single Chunk Loader be able to load chunks?
    # Allowed range: 1 ~ 6 - Default: 1
    singleChunkLoaderRadius = 1

    # In what radius should the Basic Chunk Loader be able to load chunks?
    # Allowed range: 1 ~ 6 - Default: 2
    basicChunkLoaderRadius = 2

    # In what radius should the Advanced Chunk Loader be able to load chunks?
    # Allowed range: 1 ~ 6 - Default: 3
    advancedChunkLoaderRadius = 3

    # In what radius should the Ultimate Chunk Loader be able to load chunks?
    # Allowed range: 1 ~ 6 - Default: 4
    ultimateChunkLoaderRadius = 4

    # Should chunk loaders do random ticks in loaded chunks?
    # Allowed values: true, false - Default: true
    doRandomTicks = true

