#.
#Enables/Disables the conversion of placed copycats from the single material to the multi material(where applicable) block entity. Set this to false to enable conversion! (only happens on world load, so if changed while ingame you will need to load the world again)
disableConversion = true

#.
#Enable/disable features. Values on server override clients
[features]
	copycat_wall = true
	copycat_byte = true
	copycat_wooden_pressure_plate = true
	copycat_vertical_slice = true
	#.
	copycat_vertical_stairs = true
	copycat_fence = true
	copycat_stairs = true
	copycat_shaft = true
	copycat_block = true
	copycat_vertical_step = true
	copycat_heavy_weighted_pressure_plate = true
	copycat_ghost_block = true
	copycat_half_layer = true
	copycat_slope = true
	copycat_layer = true
	copycat_stone_button = true
	copycat_wooden_button = true
	copycat_slice = true
	copycat_vertical_slope = true
	copycat_half_panel = true
	copycat_ladder = true
	copycat_stone_pressure_plate = true
	copycat_fence_gate = true
	copycat_light_weighted_pressure_plate = true
	copycat_trapdoor = true
	copycat_board = true
	copycat_beam = true
	copycat_slope_layer = true
	copycat_slab = true
#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#All copycats that can be resized by putting in more of the same copycat
	stackables = true
	#.
	#.
	#All copycats with a sloped surface
	slopes = true
	#.
	#All copycats that can emit a redstone signal
	redstone = true
	#.
	#All copycats that support multiple materials in a single block
	multistates = true
