#.
#Enables/Disables the conversion of placed copycats from old versions to new ones. Set this to false to enable conversion! (only happens on world load, so if changed while in-game you will need to load the world again)
disableConversion = true

#.
#Enable/disable features. Values on server override clients
[features]
	copycat_wall = true
	copycat_byte = true
	copycat_wooden_pressure_plate = true
	copycat_vertical_slice = true
	#.
	copycat_vertical_stairs = true
	copycat_fence = true
	copycat_stairs = true
	copycat_shaft = true
	copycat_block = true
	copycat_large_cogwheel = true
	copycat_cogwheel = true
	copycat_vertical_step = true
	copycat_iron_trapdoor = true
	copycat_heavy_weighted_pressure_plate = true
	copycat_ghost_block = true
	copycat_half_layer = true
	copycat_slope = true
	copycat_layer = true
	copycat_stone_button = true
	copycat_wooden_button = true
	copycat_slice = true
	copycat_vertical_slope = true
	copycat_half_panel = true
	copycat_ladder = true
	copycat_stone_pressure_plate = true
	copycat_fence_gate = true
	copycat_fluid_pipe = true
	copycat_light_weighted_pressure_plate = true
	copycat_iron_door = true
	copycat_trapdoor = true
	copycat_board = true
	copycat_beam = true
	copycat_slope_layer = true
	copycat_door = true
	copycat_slab = true
#.
#Enable/disable categories of features. Disabling a category hides all related features. Values on server override clients
[feature_categories]
	#.
	#All copycats with extra functions/interactions
	functional = true
	#.
	#All copycats that can be resized by putting in more of the same copycat
	stackables = true
	#.
	#All copycats mimicking blocks from Create
	create = true
	#.
	#.
	#All copycats with a sloped surface
	slopes = true
	#.
	#All copycats that can emit a redstone signal
	redstone = true
	#.
	#All copycats that support multiple materials in a single block
	multistates = true
