#Client Configuration
[client]
	[client.visual_options]
		# The maximum number of comparison tooltips to show onscreen at once.
		#Range: 1 ~ 10
		max_comparisons = 3
		# If badge_text should override the built-in translatable text.
		override_badge_text = false
		# The text shown on the badge above equipped tooltips.
		badge_text = "Equipped"
		# The color of the text shown on the badge above equipped tooltips.
		#Range: 0 ~ 4294967295
		badge_text_color = 4294967295
		# The background color of the "equipped" badge.
		#Range: 0 ~ 4294967295
		badge_bg = 4027584512
		# The start border color of the "equipped" badge.
		#Range: 0 ~ 4294967295
		badge_border_start = 3500839187
		# The end border color of the "equipped" badge.
		#Range: 0 ~ 4294967295
		badge_border_end = 1623360778
	[client.control_options]
		# If the comparison tooltip should show by default (pressing bound key hides).
		default_on = false
		# If tool comparisons should compare only the same types of tools (can't compare a sword to an axe, for example).
		strict = false
		# Item blacklist to disable comparisons for.  Add to prevent items from being compared when hovered over or equipped.  All Iceberg item selectors are supported (https://github.com/AHilyard/Iceberg/wiki/Item-Selectors-Documentation).
		blacklist = []
