# ME Extend Import/Export Bus speed multiplier
busSpeed: 8

# ME Infinity Cell idle energy cost (unit: AE/t)
infCellCost: 8.0

# ME Infinity Cell types (item or fluid's id)
infCellTypeID:
  - minecraft:water
  - minecraft:cobblestone

# The max range between two wireless connector
wirelessConnectorMaxRange: 1000.0

# The AE device/part that can be packed by ME Packing Tape
tapeWhitelist:
  - expatternprovider:ex_interface_part
  - expatternprovider:ex_pattern_provider_part
  - expatternprovider:ex_interface
  - expatternprovider:ex_pattern_provider
  - ae2:cable_interface
  - ae2:cable_pattern_provider
  - ae2:interface
  - ae2:pattern_provider
  - ae2:drive

