[spirit]
	#If set to true, any spirits dropped will simply take the form of an item.
	noFancySpirits = false

	[spirit.affinity]
		[spirit.affinity.soul_ward]
			#Multiplier for physical damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardPhysical = 0.699999988079071
			#Multiplier for magic damage taken while soul ward is active.
			#Range: 0.0 ~ 1.0
			soulWardMagic = 0.10000000149011612
			#Base time in ticks it takes for one point of soul ward to recover.
			soulWardRate = 100
	[spirit.spawner]
		#If set to true, mob spawners will create soulless mobs instead.
		lameSpawners = false
	[spirit.defaults]
		#Whether entities without spirit jsons will use the default spirit data for their category.
		defaultSpiritValues = true
[codex]
	#If set to true, the first undead enemy a player slays will drop the encyclopedia arcana.
	enableCodexDrop = true
[item]
	[item.rebound]
		#If set to true, you may put rebound on any weapon in the game.
		enableUltimateRebound = false
