#The maximum amount of items that can be queued for delivery for a mail box
mailboxInventoryRows = 1
#The maximum amount of items that can be queued for delivery for a mail box
mailQueueSize = 18
#If enabled, this will ban items with an inventory (like a Shulker Box) being sent through
#a Post Box. This prevents players from creating massive NBT on a single item, which can
#cause issues for your server/world save.
banSendingItemsWithInventories = true
#Prevents items contained in this list from being sent through a Post Box.
#An example of how the list is defined:
#bannedItems = [
#    "minecraft:water_bucket",
#    "minecraft:diamond",
#    "mighty_mail:mailbox"
#    ...
#]
#^ Note: This is just an example. Write your list below.
bannedItems = []

