enableNoEmiMessage = true
spawnWithGuideBook = true
respawnWithGuideBook = true
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = true
enableHatchPlacementOverlay = true
enableBarrelContentRendering = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
enableDefaultOreGenTooltips = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
removeIndustrialistTrades = false
